apiVersion: v1
kind: Service
metadata:
  name: svc-jenkins
  labels:
    app: jenkins
spec:   
  ports:  
  - name: "http"  
    port: 80  
    targetPort: 8080  
  selector:  
    app: jenkins
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-jenkins
  labels:
    app: jenkins
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: eks-jenkins
        image: sufiahaq/test:latest
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
